### ISSUE TITLE
How to use the custom search engine

### ISSUE THREAD

**Issue by blueyi** [azuwis/.vimfx#1]
Hi, I have your your vimfx config, it's very useful, but I couldn't use the custom search engine, only can use google for search. There is still use the default search engine(google) to search my key words when I input key `,t w someKeyWords`, rather than call Wikipedia Search engine configured by config.js. Could you help me? Thanks

**Comment by azuwis** [comment]
Use `t w someKeyWords`.

Keyword searching is Firefox's built-in feature, it works even if VimFx is not installed.
My config just adds some searching urls and associate them with keywords.

**Comment by azuwis** [comment]
FYI http://kb.mozillazine.org/Using_keyword_searches

**Comment by blueyi** [comment]
@azuwis  Thanks a lot
